### ISSUE TITLE
Index cache in docker

### ISSUE THREAD

**Issue by niquola** [HealthSamurai/us-npi#2]
We need to configure pg deployment in docker / k8s so indexes are always in memory

* https://madusudanan.com/blog/understanding-postgres-caching-in-depth/#Initial
* https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
* https://www.postgresql.org/docs/10/static/pgprewarm.html

**Comment by igrishaev** [comment]
```sql
usnpi=# SELECT c.relname, count(*) AS buffers
             FROM pg_buffercache b INNER JOIN pg_class c
             ON b.relfilenode = pg_relation_filenode(c.oid) AND
                b.reldatabase IN (0, (SELECT oid FROM pg_database
                                      WHERE datname = current_database()))
             GROUP BY c.relname
             ORDER BY 2 DESC
             LIMIT 10;
```

```
             relname             | buffers
---------------------------------+---------
 pract_trgm_idx                  |   15840
 practitioner                    |     399
 pg_class                        |      11
 pg_attribute                    |      10
 pg_proc_oid_index               |       9
 pg_proc                         |       8
 pg_attribute_relid_attnum_index |       6
 pg_operator                     |       5
 pg_operator_oprname_l_r_n_index |       5
 pg_proc_proname_args_nsp_index  |       5
(10 rows)
```

```
usnpi=# select pg_prewarm('pract_trgm_idx');
 pg_prewarm
------------
     290089
(1 row)
```

**Comment by igrishaev** [comment]
pg_buffercache extension

**Comment by igrishaev** [comment]
There should be a regular task to warm up `pract_trgm_idx` relation

**Comment by igrishaev** [comment]
http://raghavt.blogspot.ru/2014/06/utilising-caching-contribs-pgprewarm.html

**Comment by igrishaev** [comment]
how to pass `shared_buffers = 512MB` to docker?

**Comment by igrishaev** [comment]
`select pg_prewarm('pract_trgm_idx');` returns the number of blocks. Each block is 8 bytes. As the result, we need 290089 * 8 / 1024 = 2278MB for `shared_buffers` setting. The question is, how many may I allocate in config at the moment?
